version: "3.7"

services:
  database:
    image: uncaught42/doko-stats-db:${DOKO_VERSION}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DOKO_SQL_PASSWORD}
      - MYSQL_PWD=${DOKO_SQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql:rw

  server:
    image: uncaught42/doko-stats-server:${DOKO_VERSION}
    restart: always
    depends_on:
      - database
    environment:
      - DB_PW=${DOKO_SQL_PASSWORD}
    # networks:
    #   - default
    #   - traefik
    labels:
      traefik.enable: true
      # traefik.docker.network: traefik
      # http
      traefik.http.routers.doko-ws.rule: "Host(`localhost`) && Path(`/ws`)"
      traefik.http.routers.doko-ws.entrypoints: web
      traefik.http.routers.doko-ws.priority: 200
      # https
      traefik.http.routers.doko-wss.rule: "Host(`localhost`) && Path(`/ws`)"
      traefik.http.routers.doko-wss.entrypoints: websecure
      traefik.http.routers.doko-wss.priority: 200
      traefik.http.routers.doko-wss.tls: 'true'

  client:
    image: uncaught42/doko-stats-client:${DOKO_VERSION}
    restart: always
    # networks:
    #   - traefik
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.doko-webs.rule: Host(`localhost`)
      traefik.http.routers.doko-webs.entrypoints: web
    labels:
      traefik.enable: true
      # traefik.docker.network: traefik
      # http
      traefik.http.routers.doko-web.rule: "Host(`localhost`)"
      traefik.http.routers.doko-web.entrypoints: web
      traefik.http.routers.doko-web.priority: 100
      # https
      traefik.http.routers.doko-webs.rule: "Host(`localhost`)"
      traefik.http.routers.doko-webs.entrypoints: websecure
      traefik.http.routers.doko-webs.priority: 100
      traefik.http.routers.doko-webs.tls: 'true'

  proxy:
    image: traefik:v2.4.8
    restart: always
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

# networks:
#   traefik:
#     external:
#       name: traefik