version: "3.7"

services:
  database:
    image: mariadb:10.6.1-focal
    restart: always
    environment:
      - MYSQL_DATABASE=doko
      - MYSQL_ROOT_PASSWORD=sKAmqtzkQ1-QhmSdmiH2
      - MYSQL_PWD=sKAmqtzkQ1-QhmSdmiH2
    volumes:
      - ./packages/server/src/database/schema:/docker-entrypoint-initdb.d:ro
      - dblib:/var/lib/mysql:rw
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"

  proxy:
    image: traefik:v2.4.8
    restart: always
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  server:
    image: ${NODE_IMAGE}
    user: '1000:1000'
    working_dir: /doko/packages/server
    depends_on:
      - database
    volumes:
      - ./:/doko:rw
    environment:
      - NODE_ENV=development
      - LOGUX_HOST=0.0.0.0
      - LOGUX_PORT=3030
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PW=sKAmqtzkQ1-QhmSdmiH2
      - DB_NAME=doko
    entrypoint:
      - "yarn"
      - "run"
      - "dev"
    labels:
      traefik.enable: true
      # http
      traefik.http.routers.doko-ws.rule: "Path(`/ws`)"
      traefik.http.routers.doko-ws.entrypoints: web
      traefik.http.routers.doko-ws.priority: 200
      traefik.http.routers.doko-ws.service: doko-ws
      traefik.http.services.doko-ws.loadbalancer.server.port: 3030
      # https
      traefik.http.routers.doko-wss.rule: "Path(`/ws`)"
      traefik.http.routers.doko-wss.entrypoints: websecure
      traefik.http.routers.doko-wss.priority: 200
      traefik.http.routers.doko-wss.service: doko-wss
      traefik.http.routers.doko-wss.tls: 'true'
      traefik.http.services.doko-wss.loadbalancer.server.port: 3030

  client:
    image: ${NODE_IMAGE}
    user: '1000:1000'
    working_dir: /doko/packages/client
    environment:
      - BROWSER=none # see https://github.com/facebook/create-react-app/issues/7251
      - NODE_ENV=development
    volumes:
      - ./:/doko:rw
    entrypoint:
      - "yarn"
      - "start"
    labels:
      traefik.enable: true
      # http
      traefik.http.routers.doko-web.rule: "PathPrefix(`/`)"
      traefik.http.routers.doko-web.entrypoints: web
      traefik.http.routers.doko-web.priority: 100
      traefik.http.routers.doko-web.service: doko-web
      traefik.http.services.doko-web.loadbalancer.server.port: 3000
      # https
      traefik.http.routers.doko-webs.rule: "PathPrefix(`/`)"
      traefik.http.routers.doko-webs.entrypoints: websecure
      traefik.http.routers.doko-webs.priority: 100
      traefik.http.routers.doko-webs.service: doko-webs
      traefik.http.routers.doko-webs.tls: 'true'
      traefik.http.services.doko-webs.loadbalancer.server.port: 3000

  # Just for testing production build after e.g. running build.sh:
  # httpd:
  #   image: httpd:2.4-alpine
  #   volumes:
  #     - ./packages/client/build:/usr/local/apache2/htdocs:ro
  #     - ./build/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
  #   labels:
  #     traefik.enable: true
  #     traefik.http.routers.doko-web.rule: "PathPrefix(`/`)"

volumes:
  dblib:
