services:
  database:
    image: uncaught42/doko-stats-db:${DOKO_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${DOKO_SQL_PASSWORD}
      - MYSQL_PWD=${DOKO_SQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql:rw

  proxy:
    image: traefik:3.1.6
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  server:
    image: uncaught42/doko-stats-server:${DOKO_VERSION}
    depends_on:
      - database
    environment:
      - DB_PW=${DOKO_SQL_PASSWORD}
    labels:
      traefik.enable: true
      # http
      traefik.http.routers.doko-ws.rule: "Path(`/ws`)"
      traefik.http.routers.doko-ws.entrypoints: web
      traefik.http.routers.doko-ws.priority: 200
      # https
      traefik.http.routers.doko-wss.rule: "Path(`/ws`)"
      traefik.http.routers.doko-wss.entrypoints: websecure
      traefik.http.routers.doko-wss.priority: 200
      traefik.http.routers.doko-wss.tls: 'true'
      traefik.http.routers.doko-wss.tls.certresolver: myresolver

  client:
    image: uncaught42/doko-stats-client:${DOKO_VERSION}
    labels:
      traefik.enable: true
      # http
      traefik.http.routers.doko-web.rule: "PathPrefix(`/`)"
      traefik.http.routers.doko-web.entrypoints: web
      traefik.http.routers.doko-web.priority: 100
      # https
      traefik.http.routers.doko-webs.rule: "PathPrefix(`/`)"
      traefik.http.routers.doko-webs.entrypoints: websecure
      traefik.http.routers.doko-webs.priority: 100
      traefik.http.routers.doko-webs.tls: 'true'
      traefik.http.routers.doko-webs.tls.certresolver: myresolver
