services:
  database:
    image: uncaught42/doko-stats-db:${DOKO_VERSION}
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DOKO_SQL_PASSWORD}
      - MYSQL_PWD=${DOKO_SQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql:rw

  server:
    image: uncaught42/doko-stats-server:${DOKO_VERSION}
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - DB_PW=${DOKO_SQL_PASSWORD}
      - DOKO_HOST=${DOKO_HOST}
    networks:
      - default
      - traefik
    labels:
      traefik.enable: true
      # logux
      traefik.http.services.doko-stats-ws.loadbalancer.server.port: 3030
      ## http
      traefik.http.routers.doko-stats-ws.entrypoints: web
      traefik.http.routers.doko-stats-ws.priority: 200
      traefik.http.routers.doko-stats-ws.rule: "Host(`${DOKO_HOST}`) && Path(`/ws`)"
      traefik.http.routers.doko-stats-ws.service: doko-stats-ws
      ## https
      traefik.http.routers.doko-stats-wss.entrypoints: websecure
      traefik.http.routers.doko-stats-wss.priority: 200
      traefik.http.routers.doko-stats-wss.rule: "Host(`${DOKO_HOST}`) && Path(`/ws`)"
      traefik.http.routers.doko-stats-wss.service: doko-stats-ws
      traefik.http.routers.doko-stats-wss.tls.certresolver: myresolver
      traefik.http.routers.doko-stats-wss.tls: 'true'

      # api
      traefik.http.middlewares.doko-stats-api-stripprefix.stripprefix.prefixes: /api
      traefik.http.services.doko-stats-api.loadbalancer.server.port: 3000
      ## http
      traefik.http.routers.doko-stats-api.entrypoints: web
      traefik.http.routers.doko-stats-api.middlewares: 'doko-stats-api-stripprefix'
      traefik.http.routers.doko-stats-api.priority: 200
      traefik.http.routers.doko-stats-api.rule: "Host(`${DOKO_HOST}`) && PathPrefix(`/api`)"
      traefik.http.routers.doko-stats-api.service: doko-stats-api
      ## https
      traefik.http.routers.doko-stats-apis.entrypoints: websecure
      traefik.http.routers.doko-stats-apis.middlewares: 'doko-stats-api-stripprefix'
      traefik.http.routers.doko-stats-apis.priority: 200
      traefik.http.routers.doko-stats-apis.rule: "Host(`${DOKO_HOST}`) && PathPrefix(`/api`)"
      traefik.http.routers.doko-stats-apis.service: doko-stats-api
      traefik.http.routers.doko-stats-apis.tls.certresolver: myresolver
      traefik.http.routers.doko-stats-apis.tls: 'true'

  client:
    image: uncaught42/doko-stats-client:${DOKO_VERSION}
    restart: unless-stopped
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.doko-stats-web.loadbalancer.server.port: 3000
      # http
      traefik.http.routers.doko-stats-web.entrypoints: web
      traefik.http.routers.doko-stats-web.priority: 100
      traefik.http.routers.doko-stats-web.rule: "Host(`${DOKO_HOST}`)"
      # https
      traefik.http.routers.doko-stats-webs.entrypoints: websecure
      traefik.http.routers.doko-stats-webs.priority: 100
      traefik.http.routers.doko-stats-webs.rule: "Host(`${DOKO_HOST}`)"
      traefik.http.routers.doko-stats-webs.tls.certresolver: myresolver
      traefik.http.routers.doko-stats-webs.tls: 'true'

networks:
  traefik:
    name: traefik
    external: true
