version: "3.7"

services:
  # Import, e.g.:
  # cat /mnt/hgfs/VMShared/doko/doko_2020-10-02_00-46-01.sql.gz | gunzip | docker-compose exec -T database mysql doko
  database:
    image: mariadb:10.4.11-bionic
    environment:
      - MYSQL_DATABASE=doko
      - MYSQL_ROOT_PASSWORD=sKAmqtzkQ1-QhmSdmiH2
      - MYSQL_PWD=sKAmqtzkQ1-QhmSdmiH2
    volumes:
      - ./server/src/database/schema:/docker-entrypoint-initdb.d:ro
      - dblib:/var/lib/mysql:rw
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "33061:3306"

  proxy:
    image: traefik:1.7.11
    command: --api --configFile=/etc/traefik/traefik.toml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml:ro

  server:
    image: node:14.15.4-alpine3.12
    user: '1000:1000'
    working_dir: /doko/server
    depends_on:
      - database
    volumes:
      - ./:/doko:rw
    environment:
      - NODE_ENV=development
      - LOGUX_HOST=0.0.0.0
      - LOGUX_PORT=3030
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PW=sKAmqtzkQ1-QhmSdmiH2
      - DB_NAME=doko
    entrypoint:
      - "yarn"
      - "run"
      - "dev"
    expose:
      - 3030
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=PathPrefix:/api
      - traefik.port=3030

  client:
    image: node:14.15.4-alpine3.12
    user: '1000:1000'
    working_dir: /doko/client
    environment:
      - BROWSER=none # see https://github.com/facebook/create-react-app/issues/7251
      - NODE_ENV=development
    volumes:
      - ./:/doko:rw
    entrypoint:
      - "yarn"
      - "start"
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=PathPrefix:/
      - traefik.port=3000

  # Just for testing production build after e.g. running build.sh:
  # httpd:
  #   image: httpd:2.4-alpine
  #   volumes:
  #     - ./client/build:/usr/local/apache2/htdocs:ro
  #     - ./build/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
  #   labels:
  #     - traefik.enable=true
  #     - traefik.frontend.rule=PathPrefix:/

volumes:
  dblib:
